AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SAM & Laravel template using bref.

  https://github.com/aws-samples/php-examples-for-aws-lambda/blob/master/0.4-Building-A-Serverless-Laravel-App-With-AWS-SAM/template.yaml

Parameters:
  CertificateARN:
    Type: String
  DomainName:
    Type: String
  WildcardCertificateARN:
    Type: String
  Route53HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: 'The hosted zone ID which the base domain resides.'
  DbVpcId:
    Type: AWS::EC2::VPC::Id
  DbSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  DbSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  DbHost:
    Type: String
  DbSecretsARN:
    Type: String
Resources:
  Laravel:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
      Tracing: Active
      MemorySize: 1024
      CodeUri: laravel
      Layers: ["arn:aws:lambda:eu-west-1:209497400698:layer:php-80-fpm:9"]
      Handler: public/index.php
      Runtime: provided.al2
      Environment:
        Variables:
          APP_STORAGE: /tmp
          AWS_PUBLIC_BUCKET: !Ref Assets
          FILESYSTEM_DRIVER: s3
          MIX_ASSET_URL: !Join [ '', [ 'https://', !Ref DomainName, '/assets' ] ]
          ASSET_URL: !Join [ '', [ 'https://', !Ref DomainName, '/assets' ] ]
          LOG_CHANNEL: stderr
          DB_HOST: !Ref DbHost
          DB_USERNAME: !Join ['', ['{{resolve:secretsmanager:', !Ref DbSecretsARN, ':SecretString:username}}' ]]
          DB_PASSWORD: !Join ['', ['{{resolve:secretsmanager:', !Ref DbSecretsARN, ':SecretString:password}}' ]]
          SESSION_DRIVER: 'database'
  Artisan:
    Type: AWS::Serverless::Function
    Properties:
      Tracing: Active
      MemorySize: 1024
      CodeUri: laravel
      Layers: ["arn:aws:lambda:eu-west-1:209497400698:layer:console:34"]
      Handler: artisan
      Runtime: provided.al2
      Environment:
        Variables:
          APP_STORAGE: /tmp
          FILESYSTEM_DRIVER: s3
          LOG_CHANNEL: stderr
          DB_HOST: !Ref DbHost
          DB_USERNAME: !Join ['', ['{{resolve:secretsmanager:', !Ref DbSecretsARN, ':SecretString:username}}' ]]
          DB_PASSWORD: !Join ['', ['{{resolve:secretsmanager:', !Ref DbSecretsARN, ':SecretString:password}}' ]]
      VpcConfig:
        SecurityGroupIds: [!Ref SecurityGroup]
        SubnetIds: !Ref DbSubnetIds
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join [ '-', [ !Ref AWS::StackName, 'SecurityGroup' ] ]
      GroupDescription: 'The security group for the Laravel Lambda.'
      VpcId: !Ref DbVpcId
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
  AuthoriseDBAccess:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      SourceSecurityGroupId: !GetAtt SecurityGroup.GroupId
      GroupId: !Ref DbSecurityGroupId
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
  Assets:
    Type: AWS::S3::Bucket
  AssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: Assets
      PolicyDocument:
        Statement:
          Effect: Allow
          Action: s3:GetObject
          Principal:
            CanonicalUser: !GetAtt CDNIdentity.S3CanonicalUserId
          Resource: !Sub "${Assets.Arn}/*"
  Domain:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CDN.DomainName
  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        ViewerCertificate:
          AcmCertificateArn: !Ref WildcardCertificateARN
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
        Enabled: true
        Aliases: [!Ref DomainName]
        Origins:
          - Id: LaravelOriginId
            DomainName: !Join [ '.', [ !Ref ServerlessHttpApi, 'execute-api', !Ref AWS::Region, 'amazonaws.com' ] ]
            CustomOriginConfig:
              OriginProtocolPolicy: 'https-only'
          - Id: Assets
            DomainName: !GetAtt Assets.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CDNIdentity}"
        DefaultCacheBehavior:
          AllowedMethods: [ GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE ]
          TargetOriginId: LaravelOriginId
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
            # Do not forward `Host` as it messes up the API Gateway
            Headers: ['Accept', 'Accept-Language', 'Origin', 'Referer']
          ViewerProtocolPolicy: redirect-to-https
        CacheBehaviors:
          - PathPattern: 'assets/*'
            TargetOriginId: Assets
            AllowedMethods: [ GET, HEAD ]
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues: # No need for all that with assets
              QueryString: 'false'
              Cookies: {Forward: none}
            Compress: true
  CDNIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${DomainName}"
Outputs:
  Domain:
    Value: !Sub "https://${DomainName}"
  AssetsBucketARN:
    Value: !Ref Assets
